name: client testing

on:
  push:
    paths:
      - client/**
      - .github/workflows/client.yaml

env:
  NODE_ENV: test
  CLIENT_ORIGIN: http://localhost:5173
  TOKEN_SECRET: abcde12345
  PGDATABASE: recipe_app_test
  PGUSER: test_user
  PGPASSWORD: test_password

jobs:
  test:
    name: run cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: recipe_app_test
          postgresql user: test_user
          postgresql password: test_password

      - name: install client & server dependencies
        run: >
          npm --prefix client ci
          npm --prefix server ci

      - name: seed database
        working-directory: server
        run: npm run seed

      - name: run cypress component tests
        uses: cypress-io/github-action@v3
        with:
          component: true
          working-directory: client
          browser: chrome
          start: npm --prefix ../server listen, npm run dev
          wait-on: http://localhost:5173

      - name: run cypress e2e tests
        uses: cypress-io/github-action@v3
        with:
          working-directory: client
          browser: chrome
          start: npm --prefix ../server listen, npm run dev
          wait-on: http://localhost:5173
