name: server testing

on:
  push:
    paths:
      - server

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      -name: use psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'test_db'
          postgresql user: 'test_user'
          postgresql password: 'test_password'

      - name: install dependencies
        working-directory: server
        run: npm ci

      - name: run unit tests
        working-directory: server
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=test_password npm test
