name: server testing

on:
  push:
    paths:
      - server/**
      - .github/workflows/server.yaml

env:
  PGDATABASE: recipe_app_test
  PGUSER: test_user
  PGPASSWORD: test_password

defaults:
  run:
    working-directory: server

jobs:
  test:
    name: run jest unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: recipe_app_test
          postgresql user: test_user
          postgresql password: test_password

      - name: install dependencies
        run: npm ci

      - name: run jest
        run: npm test
